planning_plugin: ompl_interface/OMPLPlanner
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints
start_state_max_bounds_error: 0.1
planner_configs:
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10 # use k nearest neighbors. default: 10
  PRMstarkConfigDefault:
    type: geometric::PRMstar
  LazyPRMkConfigDefault:
    type: geometric::LazyPRM
    range: 0.0 # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
  LazyPRMstarkConfigDefault:
    type: geometric::LazyPRMstar
  PersistentPRMstar:
    type: geometric::PRMstar
    multi_query_planning_enabled: 1
    store_planner_data: 1
    load_planner_data: 0
    planner_data_path: /tmp/roadmap.graph
  PersistentPRM: # use this to load a previously created roadmap
    type: geometric::PRM
    multi_query_planning_enabled: 1
    store_planner_data: 0
    load_planner_data: 1
    planner_data_path: /tmp/roadmap.graph
  PersistentLazyPRMstar: # use this with a representative environment to create a roadmap
    type: geometric::LazyPRMstar
    multi_query_planning_enabled: 1
    store_planner_data: 1
    load_planner_data: 0
    planner_data_path: /tmp/roadmap.graph
  PersistentLazyPRM: # use this to load a previously created roadmap
    type: geometric::LazyPRM
    multi_query_planning_enabled: 1
    store_planner_data: 0
    load_planner_data: 1
    planner_data_path: /tmp/roadmap.graph

panda_arm:
  planner_configs:
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - LazyPRMkConfigDefault
    - LazyPRMstarkConfigDefault
    - PersistentLazyPRMstar
    - PersistentLazyPRM
    - PersistentPRMstar
    - PersistentPRM
panda_arm_hand:
  planner_configs:
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - LazyPRMkConfigDefault
    - LazyPRMstarkConfigDefault
    - PersistentLazyPRMstar
    - PersistentLazyPRM
    - PersistentPRMstar
    - PersistentPRM
hand:
  planner_configs:
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - LazyPRMkConfigDefault
    - LazyPRMstarkConfigDefault
    - PersistentLazyPRMstar
    - PersistentLazyPRM
    - PersistentPRMstar
    - PersistentPRM
